### ISSUE TITLE
Can't upload to Boron

### ISSUE THREAD

**Issue by TimAtFacture** [technobly/Remote-Spark#2]
Hi,

I'm trying to get started using my Particle devices with my own webpage. At first I tried getting JFlasher's spark-helper example working (http://jflasher.github.io/spark-helper/), but he has told me he is no longer supporting his Repo.

When I try to upload Remote-Spark I get this error message (https://pastebin.com/bj7ZR7n6). I have taken a quick look at the code, and have changed every reference to the Spark class to Particle to reflect the name change, but made no other changes.

I'm able to flash Tinker, as well as my own application firmware, and both of these work well with the Particle Cloud, so I don't suspect a hardware issue.

I've tried using Device OS 2.0.0 and 2.0.1 and got the same results. Compiling and flashing locally using Particle Workbench on VS Code.

I have a related post on the Particle Community Forum: https://community.particle.io/t/integrating-particle-devices-with-website/58701

**Comment by TimAtFacture** [comment]
Okay, I see now that I was still using the Photon as the target. But when I upload this firmware the device goes into safe mode, and now won't connect to the cloud even if I upload different firmware

**Comment by technobly** [comment]
Hi Tim,

I've updated the repo and both demos work ok on a Boron LTE.  They are kind of crude though with the feedback through Variable polling.

If you have the Particle CLI installed, you can put your Boron in DFU mode and run 

```
$ particle update
DFU mode again
$ particle flash --usb tinker
```

Your device should not be in safe mode anymore and should connect to the Cloud.

Then you can compile one of these apps like this:

```
DFU mode
$ particle compile boron RemoteParticle.cpp --saveTo boron-user.bin
$ particle flash --usb boron-user.bin
```

**Comment by TimAtFacture** [comment]
Thanks for the help. I'm now able to use RemoteParticle's variables and functions with the Particle console.
