### ISSUE TITLE
Can't control Boron from webpage

### ISSUE THREAD

**Issue by TimAtFacture** [technobly/Remote-Spark#3]
I have tried to control my Boron from a webpage (both locally on my computer, and uploaded to a secret URL) and I get nothing but error messages. Using the Particle Console I'm able to call functions and variables, and the LED on D7 responds to the Start/Stop function, but none of this works from the website. I have also tried this with the Simpe-Spark-Core-Controller (changing each instance of 'Spark' to 'Particle' in the firmware and index.html file) and gotten the same results.

I'm not entirely sure I'm using the correct Authentication token and device ID. For the Access token I'm using the Client Secret I obtained from the Authentications tab of the console. For the Device ID I have tried: the Client-ID which comes with the Client Secret on the Authentications tab, the ID which is listed first on the My Devices tab, and the ICCID, which I also found on the My Devices tab. There's a thread on the Particle forums where it looks like you've answered this question with pictures, but the images don't load for me (second to last post [here](https://community.particle.io/t/yes-great-but-how-do-i-get-it-on-a-web-page/1050/15))

**Comment by technobly** [comment]
Hi @TimAtFacture, you can get the Access Token with the Particle CLI.
```
$ particle token list
```
and pick a non-expired token.

The Device ID can also be found via the CLI since you are there already
```
$ particle list

device-name [device-id] (Boron) is online
```

**Comment by TimAtFacture** [comment]
Got it, thanks
